server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: debugathon
    password: debugathon
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    distribution:
      percentiles-histogram:
        payment_request_duration_seconds: true
