server:
  port: 8080

orchestrator:
  service:
    base-url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
