server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orchestratordb
    username: debugathon
    password: debugathon
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

payment:
  service:
    base-url: http://localhost:8082

operator:
  service:
    base-url: http://localhost:8083
  timeout-ms: 2000
  retry:
    max-attempts: 2

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    distribution:
      percentiles-histogram:
        booking_request_duration_seconds: true
        operator_request_duration_seconds: true
